### ISSUE TITLE
Attempt to delete image (when no longer exists)

### ISSUE THREAD

**Issue by RWAP** [cloudinary/cloudinary_php#67] opened 2017-03-10 12:01 UTC
I have come across an odd issue.

I use ajax to pass the details of images as they are uploaded back to my server, and again use the same call if a user decides to delete an image.

The code for deleting sometimes times (it would appear) - basically no data is returned by the server.

Having investigated, the issue is around the commands:

				`$result = \Cloudinary\Uploader::destroy($cloudinaryId);`

This normally works fine and my code returns a flag to let the ajax know that the image has been removed from the database lookup and cloudinary.

However, if the cloudinaryId has already been destroyed once, then I get the issue of nothing being returned by the JSON call.  There is nothing in the PHP error logs, so I assume the destroy call is simply stuck somewhere.

Is there a means of checking if the cloudinary id is valid before calling this routine (maybe) ?

**Comment by RWAP** [comment] 2017-03-10 12:20
Hmm - I have just logged onto my cloudinary account and can see the image in the media library with the correct cloudinary id.  If I comment out the line above, then the JSON call returns successfully.

I guess it is some other error within the cloudinary code which is not being trapped....

**Comment by roeeba** [comment] 2017-03-12 14:54
Hi @RWAP, can you please share with us your cloud_name and the timeframe in which you've made these actions so we check your logs for the cause of this behaviour?

**Comment by RWAP** [comment] 2017-03-12 19:05
Cloud name is dtf2gwjcg - these actions were occuring when I first opened this issue - so approx 11am (UK time) on 12/3/17

**Comment by roeeba** [comment] 2017-03-14 13:29
Thanks @RWAP, Looking at the logs I see only 200 response. Can you please also share with me a couple of example public_ids so we can investigate it further? if you'd like to keep this private, please feel free to open a [support ticket](https://support.cloudinary.com/hc/en-us/requests/new). Thanks.

**Comment by RWAP** [comment] 2017-03-14 13:41
Does the PHP code for cloudinary disable error reporting?  I have it enabled by default on the server (as it is a development server), but obviously the return from the call with just blank information suggests an unlogged / non-captured PHP error.

The image uploads at the time seemed to work without issue, it was the image deletes which were failing - but odd there is nothing in your logs, or in the logs on my own server.

I will try to replicate it again and then provide some public_ids by way of example, since it is only a test site at the moment.

**Comment by roeeba** [comment] 2017-06-14 12:13
Hi @RWAP, I apologise for the very late reply. Are you still having issues with deleting files?

**Comment by roeeba** [comment] 2017-09-25 10:20
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2017-09-25 10:20 UTC
